### PR TITLE
Fix Duplicate Key and MySQL Column issues

### PR DESCRIPTION
**Pull request by acaire**
PR Attempt to resolve some outstanding issues - The tests are currently very broken and I need some feedback. They involved making this change in the errbot source in an attempt to test backups/restores:

``` shell
diff --git a/errbot/backends/test.py b/errbot/backends/test.py
index dd0b5fd..def42ef 100644
--- a/errbot/backends/test.py
+++ b/errbot/backends/test.py
@@ -343,10 +343,13 @@ class TestBot(object):
     """
     bot_thread = None

-    def __init__(self, extra_plugin_dir=None, loglevel=logging.DEBUG, extra_config=None):
-        self.setup(extra_plugin_dir=extra_plugin_dir, loglevel=loglevel, extra_config=extra_config)
+    def __init__(self, extra_plugin_dir=None, loglevel=logging.DEBUG,
+                 extra_config=None, restore_backup=None):
+        self.setup(extra_plugin_dir=extra_plugin_dir, loglevel=loglevel,
+                   extra_config=extra_config, restore_backup=restore_backup)

-    def setup(self, extra_plugin_dir=None, loglevel=logging.DEBUG, extra_config=None):
+    def setup(self, extra_plugin_dir=None, loglevel=logging.DEBUG,
+              extra_config=None, restore_backup=None):
         """
         :param extra_config: Piece of extra configuration you want to inject to the config.
         :param extra_plugin_dir: Path to a directory from which additional
@@ -354,7 +357,12 @@ class TestBot(object):
         :param loglevel: Logging verbosity. Expects one of the constants
             defined by the logging module.
         """
-        tempdir = mkdtemp()
+        if restore_backup:
+            self.restore = True
+            tempdir = restore_backup
+        else:
+            self.restore = False
+            tempdir = mkdtemp()

         # This is for test isolation.
         config = ShallowConfig()
@@ -388,7 +396,7 @@ class TestBot(object):
         """
         if self.bot_thread is not None:
             raise Exception("Bot has already been started")
-        self._bot = setup_bot('Test', self.logger, self.bot_config)
+        self._bot = setup_bot('Test', self.logger, self.bot_config, self.restore)
         self.bot_thread = Thread(target=self.bot.serve_forever, name='TestBot main thread')
         self.bot_thread.setDaemon(True)
         self.bot_thread.start()
```

Which seems terrible, but i'm not sure on the best way to achieve this.  Furthermore, the bot state isn't properly reloaded between tests, so I guess I could run run py.test separately three times but that also seems super hacky... Thoughts?

### CODE REVIEW

**Comment by brycied00d** [comment]
I've been running this branch for about an hour now, everything's working great. 

In addition to #2, I was having issues when plugins tried to update/set parameters due to err-storage-sql trying to `INSERT` the new data which conflicts against the constraint and existing row. This branch rectifies that problem.

**Comment by zoni** [comment]
I merged all but the last commit (containing the tests) of this branch into master so that this storage backend is usable for MySQL users.

I love the work on the tests done here but it's too extensive for me to work on right now given other priorities. Perhaps @gbin has some thoughts here though.

**Comment by brycied00d** [comment]
> so that this storage backend is usable for MySQL users.

And Postgres (thanks to     b54794e)!

**Comment by zoni** [comment]
Good point :grinning:

**Pull request closed without merging**
